services:
    rxu.detailed_viewonline.listener:
        class: rxu\detailed_viewonline\event\listener
        arguments:
            - @config
            - @dbal.conn
            - @user
            - @auth
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }
